name: 自动转换adguard规则工作流

on:
  schedule:
    # 每天北京时间 03:30（对应 UTC 19:30）
    - cron: '30 19 * * *'
  workflow_dispatch:  # 手动触发按钮

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行转换脚本
        run: python convert_adguard_to_clash.py

      - name: 提交更改
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add convert_adguard_to_clash.list
          git commit -m "每日自动更新 Clash 规则列表" || echo "No changes to commit"
          git push
