# .github/workflows/merge_rules.yml
# 此工作流在仓库根目录下运行 merge_rules.py，合并并排除规则，生成并提交 Ruleset/Merged 目录

name: 合并规则工作流
permissions:
  contents: write

concurrency:
  group: merge-rules
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run merge script
        run: python merge_rules.py

      - name: List merged files
        run: ls -R Ruleset/Merged

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Auto merge and update rules'
          add: 'Ruleset/Merged'

# 使用说明：
# 1. 确保仓库根目录有 merge_rules.py 和 merge_config.json。
# 2. merge_rules.py 会读取 merge_config.json，按配置合并并排除规则。
# 3. 通过 Actions 手动触发或定时触发，生成的规则文件会自动提交到 Ruleset/Merged。
# 4. 若需调整调度时间，修改 cron 表达式即可。
