# .github/workflows/merge_rules.yml
name: 合并规则工作流
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'  # 每天 UTC 19:00（北京时间凌晨3点）

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 运行合并脚本
        working-directory: ${{ github.workspace }}   # 默认就是仓库根目录
        run: python merge_rules.py

      - name: 提交并推送更新
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: '自动合并更新 Clash 规则'
          add: 'Ruleset/Merged'
