name: 更新广告屏蔽规则

# 定时与手动触发
on:
  schedule:
    - cron:  '0 0 * * *'      # UTC 每天 00:00 运行 → 北京时间 08:00 :contentReference[oaicite:2]{index=2}
  workflow_dispatch:         # 手动触发

permissions:
  contents: write            # 允许写入仓库内容 :contentReference[oaicite:3]{index=3}

jobs:
  merge_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 获取完整历史，确保能推送所有分支 :contentReference[oaicite:4]{index=4}

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests PyGithub

      - name: 运行合并脚本
        run: python merge_ads_rules.py

      - name: 提交并推送更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Ruleset/AdsUnified.list
    # 如果有差异，就提交，否则跳过
          if git diff --cached --exit-code; then
            echo "无更新，跳过提交"
          else
            git commit -m "自动更新 AdsUnified.list (由 GitHub Actions)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

