name: Merge Clash Rules
on:
  schedule:
    - cron: '0 19 * * *'   # 每天 UTC 19:00（北京时间凌晨3:00）10
jobs:
  merge:
    permissions:
      contents: write    # 赋予写权限以便推送更新11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行合并脚本
        run: python merge_rules.py

      - name: 提交并推送更新
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "自动合并更新 Clash 规则"
          add: "Ruleset/Merge"
