name: 更新广告屏蔽规则

# 定时与手动触发
on:
  schedule:
    - cron:  '0 0 * * *'      # UTC 每天 00:00 运行 → 北京时间 08:00 :contentReference[oaicite:2]{index=2}
  workflow_dispatch:         # 手动触发

permissions:
  contents: write            # 允许写入仓库内容 :contentReference[oaicite:3]{index=3}

jobs:
  merge_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 确保 Ruleset 目录存在
        run: mkdir -p Ruleset

      - name: 运行合并脚本
        run: python merge_ads_rules.py

      # —— 临时加入调试步骤 —— #
      - name: 列出当前目录结构
        run: ls -R .

      - name: 查看生成的规则文件前十行
        run: head -n 10 Ruleset/AdsUnified.list || echo "文件不存在"

      # —— 调试结束 —— #

      - name: 提交并推送更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Ruleset/AdsUnified.list
          if git diff --cached --exit-code; then
            echo "无更新，跳过提交"
          else
            git commit -m "自动更新 AdsUnified.list"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
